site_name: WSO2 API Manager Documentation

# Repository
repo_name: View on Github
repo_url: https://github.com/sherenewso2/mkdocs-base

nav:
    - Getting Started:
      - 'Introduction': 'GettingStarted/Overview.md'
      - 'About this release': 'GettingStarted/About_this_Release.md'
      - 'Quick Start': 'GettingStarted/QSG.md'
    - Concepts: 
      - 'Introduction': 'GettingStarted/Overview.md'
      - 'Identity_Provisioning and its Standards': 'Concepts/Identity_Provisioning_and_its_Standards.md'
      - 'Access_Control and Entitlement Management': 'Concepts/Access_Control_and_Entitlement_Management.md'
      - 'Identity Anti-patterns and the Identity Bus': 'Concepts/Identity_Anti-patterns_and_the_Identity_Bus.md'
    - How Tos:
      - 'Troubleshooting Guide': 'GettingStarted/Overview.md'
      - Best Practices Guide: 
        - BestPracticesGuide/index.md
        - Testing: 'Developer_Guide.md'
      - 'Developer Guide': 
        - Testing: 
          - WUM Commands Guide: 'WUM_Commands_Guide.md'
        - Another subpage:
          - Develop: 'Developer_Guide.md'
    - Develop:
      - User Management for Developers:
        - Writing a Custom Password Validator: 'GettingStarted/Overview.md'
        - Writing a Custom Claim Handler: 'Develop/user_mgt/Writing_a_Custom_Claim_Handler.md'
        - User Store Listeners: 'Develop/user_mgt/User_Store_Listeners.md'
        - Using the User Management Errors Event Listener: 'Develop/user_mgt/Using_the_User_Management_Errors_Event_Listener.md'
        - Carbon Remote User Store Manager: 'Develop/user_mgt/Carbon_Remote_User_Store_Manager.md'
      - Provisioning for Developers:
        - Writing an Outbound Provisioning Connector: 'GettingStarted/Overview.md'
        - Extensible SCIM User Schemas With WSO2 Identity Server: 'Develop/provision/Extensible_SCIM_User_Schemas_With_WSO2_Identity_Server.md'
      - Identity Federation for Developers:
        - Writing a Custom Federated Authenticator: 'GettingStarted/Overview.md'
        - Writing a Custom Local Authenticator: 'Develop/federate/Writing_a_Custom_Local_Authenticator.md'
    - Admin:
      - 'Introduction': 'GettingStarted/Overview.md'
      - 'Using WSO2 In-Place Updates': 'Using_WSO2_In-Place_Updates.md'
    - Deploy:
      - 'Introduction to APIM Deployment': 'Deploy/introduction_apim_deployment.md'
      - 'Deployment Patterns': 'Deploy/deployment_patterns.md'
      - 'Configuring a Single Node Deployment': 'Deploy/single_node_deployment.md'
      - 'Configuring a Single Node HA Deployment': 'Deploy/active_active_deployment.md'
      - 'Configuring a Fully Distributed Deployment': 'Deploy/fully_distributed_deployment.md'
      - Supporting Configurations:
        - 'Configuring Databases for APIM': 'Deploy/configuring_db_for_apim.md'
        - 'Configuring Load Balancing': 'Deploy/configuring_load_balancing.md'
        - 'Troubleshooting Deployment': 'Deploy/troubleshooting_apim_deployment.md'
      - Optional Configurations:
        - 'Configuring RSync for Deployment Synchronization': 'Deploy/rsync_dep_synchronization.md'
        - 'Configuring WSO2 Identity Server as Key Manager' : 'Deploy/using_is_as_key_manager.md'
        - 'Configuring APIM Analytics': 'Deploy/analytics_deployment.md'
      - 'Product Deployment Checklist': 'Deploy/deployment_guidelines.md'
    - Config Catalog:
      - 'APIM Configurations': 'all_configs/all_product_configs.md'
    - Troubleshooting:
      - 'Introduction': 'GettingStarted/Overview.md'
      - 'Using WSO2 In-Place Updates': 'Using_WSO2_In-Place_Updates.md'
    - References:
      - 'API Docs': 'all_configs/api_catalog.md'
      - 'Properties Catalog': 'all_configs/properties_catalog.md'
      - 'Config Catalog': 'all_configs/all_product_configs.md'
    - Community:
      - 'Introduction': 'GettingStarted/Overview.md'
      - 'Using WSO2 In-Place Updates': 'Using_WSO2_In-Place_Updates.md'

theme:
  name: 'material'
  palette: 
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Nunito Sans'
    code: 'Courier New'
  logo: 'images/WSO2_Software_Logo.png'
  language: 'en'
  feature:
    tabs: true  

markdown_extensions:
 - markdown_include.include:
     base_path: docs
 - admonition
 - codehilite
 - pymdownx.arithmatex
 - pymdownx.betterem:
     smart_enable: all
 - pymdownx.caret
 - pymdownx.critic
 - pymdownx.details
 - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
 - pymdownx.inlinehilite
 - pymdownx.magiclink
 - pymdownx.mark
 - pymdownx.smartsymbols
 - pymdownx.superfences
 - pymdownx.tasklist:
     custom_checkbox: true
 - pymdownx.tilde
 - toc:
       title: Contenu
       permalink: True
       baselevel: 3
